### ISSUE TITLE
Default Controller Profiles are not centered properly

### ISSUE THREAD

**Issue by JazzyFuture** [Struggleton/Delfinovin#11]
When calibrating the controller, it goes back to neutral position, but as soon as I finish calibrating, it always goes back to constantly inputting that direction. It worked normally for a while so idk what's happened. Might be something with default controller profiles.

**Comment by JazzyFuture** [comment]
Ok so the issue is when loading a controller profile at startup. If you have set up a controller to use a default profile, it will mess up the stick inputs.

**Comment by Struggleton** [comment]
@JazzyFuture I released a hotfix for the issue last night - redownload and see if the issue persists

**Comment by Struggleton** [comment]
Marking as fixed as I assume the hotfix remedied this.
