### ISSUE TITLE
CultureInfo issue on profile save

### ISSUE THREAD

**Issue by xdanieldzd** [Struggleton/Delfinovin#13]
Saving a controller profile in Delfinovin results in an unusable file on my German-language Windows 10 install.

German uses the comma as a decimal separator, but currently, the program will save the trigger and deadzone floats in the ControllerSettings class without specifying a culture (i.e. defaulting to the system culture, so using comma decimal separator for me), while loading them using ```CultureInfo.InvariantCulture``` (which uses periods as decimal separators).

The saved profile thus ends up looking like this:
```
TriggerDeadzone: 0,23
TriggerThreshold: 0,65
LeftStickDeadzone: 0,23
LeftStickRange: 0,85
RightStickDeadzone: 0,23
RightStickRange: 0,85
...
```
...which makes Delfinovin v1.0 interpret the values as such:

![Bad values](https://user-images.githubusercontent.com/7199225/129582557-12b1831c-8356-4798-9a54-4c0b506062f0.png)

...resulting in non-working triggers and sticks. Manually replacing the commas with periods using a text editor will fix the profile, allowing Delfinovin to load it correctly.

**Comment by Struggleton** [comment]
Thanks for the report - I've specified it to use the US-Culture formatting in commit https://github.com/Struggleton/Delfinovin/commit/5b952ed51fdd8610e7c526eb31cd72a2b7310726 and [build v1.0.1](https://github.com/Struggleton/Delfinovin/releases/tag/v1.0.1).

**Comment by xdanieldzd** [comment]
Can confirm that both loading and saving work correctly for me using v1.0.1, thanks for the quick fix!
