### ISSUE TITLE
Controller cannot be detected upon reopening Delfinovin

### ISSUE THREAD

**Issue by Nicotorednico6** [Struggleton/Delfinovin#14]
Opening Delfinovin for the first time on boot finds the controller normally. Closing and reopening it causes it to not be detected. Disabling WUP driver in device manager and reenabling it fixes this.

**Comment by Struggleton** [comment]
Are you sure that the controller adapter is not being used by another application when you reopen it? Delfinovin when it closes it releases its control over the adapter which allows other softwares like Yuzu and Dolphin to take over and make it not be detectable by Delfinovin.
