### ISSUE TITLE
Profiles aren't correctly applied

### ISSUE THREAD

**Issue by Sidilium** [Struggleton/Delfinovin#15]
When Delfinovin applies a profile, it just puts every value except stick deadzones at 100%, so I have to redo my profile every time I open the program.

**Comment by Struggleton** [comment]
There's a dialog in the application to select a profile to load on a specific port. Are you setting it there? 
![image](https://user-images.githubusercontent.com/17230330/132025692-fd311bbf-2e7b-43f0-a548-578310f07997.png)

**Comment by Sidilium** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/17230330/132025692-fd311bbf-2e7b-43f0-a548-578310f07997.png)
> 
> There's a dialog in the application to select a profile to load on a specific port. Are you setting it there? You make a profile + save it and then set it to load in that application settings dialog.

I have set these settings as displayed in your screenshot, but when I open and close the program, the values reset to 100%

**Comment by Struggleton** [comment]
Send your profile file. Should be in the profiles folder in the same directory as Delfinovin

**Comment by Sidilium** [comment]
[Name.txt](https://github.com/Struggleton/Delfinovin/files/7110798/Name.txt)

**Comment by Struggleton** [comment]
Try downloading the most recent version of Delfinovin and creating a new profile with the same settings. I fixed that issue in v1.0.1

**Comment by Sidilium** [comment]
> 
> 
> Try downloading the most recent version of Delfinovin and creating a new profile with the same settings. I fixed that issue in v1.0.1

It works with the latest release! Thank you. I like this program 👍

**Comment by Struggleton** [comment]
No problem!
