### ISSUE TITLE
DelfinovinUI stays open in background when closing via taskbar

### ISSUE THREAD

**Issue by Sim0nV** [Struggleton/Delfinovin#18]
Hi!

Just a minor issue: for me, DelfinovinUI stays open in the background closing via the taskbar. 
Closing Delfinovin by clicking the X in the application works fine, just not when I close it via the taskbar.

Here is a video: [https://streamable.com/d7whxq]( https://streamable.com/d7whxq)

As you can see, when closing Delfinovin via the taskbar, DelfinovinUI remains open even though it does not show on the taskbar nor the system tray.

This means I can still use my GCC as an Xbox controller after closing which is nice, but I'm not sure if this is intended behavior since it may not be apparent to the user that it is still open. If I want to switch back to native Zadig, say for Slippi, I have to exit out of Delfinovin using the task manager.

Thank you for your time! Delfinovin is amazing btw

**Comment by Struggleton** [comment]
Sorry for the extremely slow response to this issue. This issue is fixed in commit [7018cb7](https://github.com/Struggleton/Delfinovin/commit/7018cb743207a35be419de642e9ac7872f330109).
