### ISSUE TITLE
Mayflash 4-port adapter

### ISSUE THREAD

**Issue by flagrama** [Struggleton/Delfinovin#19]
The Mayflash adapter is not meant to be used on PC with the custom WUP-028 driver. It has a PC mode that makes it a DirectInput device and if someone wants XInput from it they should use a DInput to XInput mapper, or you should implement a DInput to Xinput mapper for that case.

There are two problems with using the custom driver with Mayflash. 

1. If you do not tell users to use Wii U/Switch mode they will install it over the PC mode device and cause the device to no longer work at all in PC mode until they force reinstall the generic USB Input Device driver over it again or reinstall their OS
2. From personal experience I know the installation of the custom driver can brick the driver entirely until a reinstall of the OS, and while on devices that do not have a PC mode this is a risk you need to take to get it to work, and even though it isn't likely to happen, it is not a risk users of Mayflash devices should take.

**Comment by Struggleton** [comment]
Thanks for the heads-up! I had wrote this in the FAQ but forgot to write it in the main readme.
