### ISSUE TITLE
Delfinovin won't launch when there's a default profile selected

### ISSUE THREAD

**Issue by Watermalia** [Struggleton/Delfinovin#20]
Without a default profile, the program launches just fine.
However, when there is a default profile for a controller (I've only tested using Controller #1), the program won't launch and I had to delete the settings.txt to get it to launch again.

**Comment by JaiChong** [comment]
To add on, Delfinovin did work with profiles for me for a few weeks, but then suddenly and consistently stopped opening if settings.txt had any profiles saved.  It fails to open even as a fresh install with just the profiles folder and settings.txt folder replaced.

**Comment by Struggleton** [comment]
I apologize for the extremely slow response to this issue. Could you upload your settings.txt file and the profile in the profiles folder? @JaiChong or @Watermalia

**Comment by JaiChong** [comment]
I've since deleted the failed settings.txt files, and started loading them manually each time to avoid the issue, sorry.  I'll start using the default profiles feature again, but it no longer prevents launches for now.  I'll upload if it happens again, though it may be best if we all do so until it possibly happens.  I did compare the contents of the bugged settings.txt file with a fresh one and didn't notice a difference, but I might have just missed something.  I did not check the profile files for differences.

**Comment by JaiChong** [comment]
settings.txt started preventing bootup today, but the issue doesn't seem to remain after zipping, unzipping, and launching delfinovin with the same settings.txt file.  The contents are identical to a working settings.txt file.  Either way, I don't think the settings.txt file is the problem itself.

When a new settings.txt file is created, are file directory paths reset?  Are they changed by any other functions?

**Comment by JaiChong** [comment]
Broke again, so did some more testing this time.  From a bugged root folder:
- Deleting the assigned profiles in the bugged settings.txt file (or deleting the whole file) allows Delfinovin.exe to launch.
- Saving assigned profiles through the Delfinovin Settings window crashes Delfinovin.exe.
- The bug persists until either the root folder is either zipped and extracted elsewhere as a separate instance, or replaced (deleted and a fresh root folder is extracted).

**Comment by Struggleton** [comment]
Hi there! Thanks for the follow-up on testing this stuff! I'll be implementing a new profiles/settings system using JSONs and rewriting how it interacts with the program in the next version, which should hopefully fix some of the issues people are having with the profile loading. Thank you so much @JaiChong

**Comment by Struggleton** [comment]
Fixed in [version 3.0.0!](https://github.com/Struggleton/Delfinovin/releases/tag/v3.0.0) Closing.
