### ISSUE TITLE
Launching the program with the adapter already plugged in won't detect the adapter

### ISSUE THREAD

**Issue by Watermalia** [Struggleton/Delfinovin#21]
If the gamecube adapter is already plugged in when launching the program, the adapter won't get detected until I replug the adapter

**Comment by ProGaro** [comment]
@Watermalia What type of adapter are you using?

**Comment by Watermalia** [comment]
The official Wii U GCC adapter

**Comment by ProGaro** [comment]
@Watermalia Do you have the latest Zadig drivers installed?

**Comment by Struggleton** [comment]
Sorry for the slow response to this issue. I'm unable to replicate this issue, but if it's still persisting, one thing you might be able to try is reinstalling the Zadig (WinUSB) driver and restarting Delfinovin.

**Comment by Struggleton** [comment]
This should be fixed in Delfinovin [version 3.0.0](https://github.com/Struggleton/Delfinovin/releases/tag/v3.0.0) - closing as discussion is inactive.
