### ISSUE TITLE
Please add custom controller binding.

### ISSUE THREAD

**Issue by TonicGaro** [Struggleton/Delfinovin#22]
Ok so I've using this program for a couple of days now and I have to say this program is really good! The only problem I have is that there is barely any controller binding customization. The only custom binding that is in the program is swapping the AB and XY buttons which is very limiting. If you could make it to where we can bind a button on the GameCube controller to any button on the Xbox controller that would be amazing.

**Comment by Struggleton** [comment]
Sorry for the extremely slow response to this - but this is still in the works. The feature should allow you to remap buttons and map multiple buttons to a single press. (ex: a+b press = X press, etc.)

**Comment by MarUlberg** [comment]
I second this. I would really like to see, if not full remapping, at least a swap B/X feature for the purpose of emulating the Xbox controller layout. Otherwise, thanks for a great program.

**Comment by Struggleton** [comment]
Added in [version 3.0.0!](https://github.com/Struggleton/Delfinovin/releases/tag/v3.0.0) Closing.
