### ISSUE TITLE
Registers my gamecube adapter but not my game cube controller

### ISSUE THREAD

**Issue by sammym67** [Struggleton/Delfinovin#25]

**Comment by Struggleton** [comment]
Hi! What kind of controller and GCC adapter are you using? If you're using a third party controller, could you see if it works with both the black and grey cords plugged in at the same time?

**Comment by sammym67** [comment]
I am using a nitendo official controller with a cheap adapter i found on amazon,
it might be the adapter but the software was working fine until a couple of days ago?
I also have tried pugging in both cords at the same time.

**Comment by travchka** [comment]
Hi, having the same issue. [I am using this adapter](https://www.amazon.fr/Adaptateur-Manette-Gamecube-pour-Wii/dp/B00O9QW4JQ)

[here's what it shows me after installing everything](https://cdn.discordapp.com/attachments/891396796453105756/1002697590904733696/Screenshot_1.jpg)

I have tried with one/both cords plugged, tried every port with different controllers (have 4 total), says adapter is connected,  vigembus connected but can't get a controller on.

**Comment by sammym67** [comment]
Hi, I am seeing the same thing, please let me know if you find a fix.

**Comment by 1Sens** [comment]
same here everytime i tab out of it after opening im not able to open it anymore, but tells me its running still

**Comment by Struggleton** [comment]
Closing issue as discussion is inactive.
