### ISSUE TITLE
Crash on clicking Settings or Controller Profiles

### ISSUE THREAD

**Issue by Qualzz** [Struggleton/Delfinovin#27]
The program crash and close when I press the Settings button or the Controller Profiles button. 

Windows 11 OS - French OS language. 

Also, maybe related, it doesn't save any settings when closing and reopenning the app.

**Comment by Struggleton** [comment]
Hi there - check my response to this issue on is #20! I'll be implementing a new settings system soon in a new version of Delfinovin which should fix a number of bugs with the system.
