### ISSUE TITLE
Stick drift

### ISSUE THREAD

**Issue by NiteCyper** [Struggleton/Delfinovin#28]
<img width="623" alt="DelfinovinUI_GQtVCdmZgG" src="https://user-images.githubusercontent.com/5100510/185753313-163f874c-36fb-44fb-91e4-3e10983e77fb.png">
My joystick is off-center now. Wasn't like this before. Wtf why. It works fine with Melee. My PhobGCC doesn't have the same problem. I've tried a bunch of things. The only way to fix it now is to set the stick in the drifted position so it becomes the new center/neutral after I plug it in and let go. Calibration does nothing.

**Comment by JaiChong** [comment]
If you hold X+Y+Start to trigger the controller's manual reset, it should return to neutral.  I have the same issue every time on my controller since it has a mod that fixes stick drift (forget the name)

**Comment by Struggleton** [comment]
Closing as discussion is inactive.
