### ISSUE TITLE
ViGEmBUs issue

### ISSUE THREAD

**Issue by Mistymimi** [Struggleton/Delfinovin#29]
Delfino isn't recognizing my installation of ViGEmBus. I tried reinstalling it and repairing it several times, but delfino keeps saying it isn't installed. I'm using the most recent version of ViGEmBus at time of writing: 1.20.432.

**Comment by MatthewRak** [comment]
I'm having the same issue -- tried the most recent pre-release 1.20.432 and the latest release 1.18.367.0.

**Comment by Struggleton** [comment]
Sorry for the slow response, I'm looking into the issue now. Could you try using [ViGEmBus Setup 1.16.116](https://github.com/ViGEm/ViGEmBus/releases/tag/setup-v1.16.116) in the mean time?

**Comment by Struggleton** [comment]
Closing this issue as discussion has been inactive.
