### ISSUE TITLE
Not Launching Consistently

### ISSUE THREAD

**Issue by NotTill4** [Struggleton/Delfinovin#44]
I have an issue where Delfinovin will not consistently open. If I launch it normally, it usually opens but does not display anything. It shows up in my task manager but does not work. If I close it and try to run as administrator, it sometimes works, or does not open at all. I usually have to restart my computer and try again until it opens as it should. It only ever opens properly when I run as administrator.

**Comment by Struggleton** [comment]
If it is only opening when opened as an Administrator, it may have to do with your antivirus (if you have one) flagging it as a false positive. If so, try checking your AV settings and seeing if you can see a whitelist for Delfinovin to open.
