### ISSUE TITLE
Holding multiple buttons on the controller causes Delfinovin to stop reading button inputs

### ISSUE THREAD

**Issue by AyjayJr** [Struggleton/Delfinovin#45]
When I hold start + a + x + y on my controller Delfinovin seems to lose all detection of input until I let go.

I'm using a GCN Controller and a cheap third party adapter.

**Comment by saltypepper14** [comment]
If you hold X + Y + Start for 3 seconds, the controller automatically disconnects to reset itself. This isn't a problem with Delfinovin it's just how Gamecube controllers work
