### ISSUE TITLE
Dolfinovin won't run

### ISSUE THREAD

**Issue by MarvinGdt** [Struggleton/Delfinovin#5]
When i want to use Dolfinovin, i have this error message : https://imgur.com/qT7DVTF
Everything is set up. ViGEm installed, zadig driver aswell.

**Comment by Struggleton** [comment]
Fixed in commit [b830a8f!](https://github.com/Struggleton/Delfinovin/commit/b830a8f86286726d4679315c5c1beba19e8ca170)
