### ISSUE TITLE
Implement Manual Stick Ranges

### ISSUE THREAD

**Issue by NageMcPollo** [Struggleton/Delfinovin#6]
Similar to how the yuzu emulator has a range percentage setting for both analog sticks. Its fine enough within yuzu but when I want to play other games in my pc, the left analog doesn't register a full 100% direction and calibrating the stick both on delfinovin and in control panel doesnt solve the problem for some reason. Could there be an option to do this in the settings file like the deadzone value?

**Comment by Struggleton** [comment]
Definitely possible! I was just thinking about giving the option to do that. Will look into doing so in the next couple days!

**Comment by MutantAura** [comment]
Definitely interested in this. While yuzu has this implemented in software I usually play single player content in Ryujinx which does not have range modification in their input settings. 
Would love to have full stick control like I do with the trigger ranges etc.

**Comment by Struggleton** [comment]
This is still definitely in the works - Currently working on the UI for Delfinovin which'll make setting these ranges and other settings much more inuitive than setting it in the settings file.

**Comment by Struggleton** [comment]
Added in the [wpf-ui branch](https://github.com/Struggleton/Delfinovin/tree/wpf-uidev) of Delfinovin @NageMcPollo @MutantAura  + the latest release
