### ISSUE TITLE
Remapping XInput Buttons

### ISSUE THREAD

**Issue by bowiz2** [Struggleton/Delfinovin#9]
This is the first tool that I found that gets my gamecube adapter to actually work with PC games - and it's incredible!

But the games I've tried have non intuitive button mappings, like B mapped to A.
Is there a way to remap inputs? Even if it's a hacky way at the moment, like me needing to keep multiple settings files and renaming them to `settings.txt` when necessary.

If there's another tool that's meant to solve this problem just point me to it!

**Comment by Struggleton** [comment]
This'd be pretty easy to add as a setting. I can add this to the next release of Delfinovin

**Comment by Struggleton** [comment]
Added in commit [#d79bcb1](https://github.com/Struggleton/Delfinovin/commit/d79bcb1964049d4a0c5276d258d7b5034ebe4763)!
